#!/bin/sh

# posix
# this file looks through all the files in the current
# directory for the string POSIX and then prints 
# those files to the standrad output

for file in *
do 
    if grep -q POSIX $file;
    then 
        echo $file
    fi
done

exit 0

